spring:
  application:
    name: behavior-data-service # 与子模块ArtifactId一致
  config:
    import: nacos:behavior-data-service.yml
  cloud:
    nacos:
      discovery:
        server-addr: 134.175.123.61:8848
      config:
        server-addr: 134.175.123.61:8848
        file-extension: yml
        group: DEFAULT_GROUP # Nacos配置分组（默认即可）
    sentinel:
      transport:
        dashboard: 134.175.123.61:8080 # 连接Sentinel控制台
      eager: true # 饥饿加载（启动时就注册到Sentinel）
  datasource:
    url: jdbc:mysql://134.175.123.61:3306/db_behavior?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root # 你的MySQL用户名
    password: ljl20021018 # 你的MySQL密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 134.175.123.61
    port: 6379
    password:
    database: 2 # 行为服务专用Redis数据库
  rabbitmq:
    host: 134.175.123.61
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual # 手动ACK（确保消息不丢失）

server:
  port: 9001 # 独立端口（不与其他服务冲突）
  servlet:
    context-path: /

# MyBatis-Plus配置（适配新包名）
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml # 资源目录下的mapper文件
  type-aliases-package: com.gdut.behaviordata.entity # 实体类包路径
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL日志

logging:
  level:
    com.gdut.behaviordata.mapper: debug